---
name: Auto Catalogue Updater
on: 
  release:
    types: [published]
  push:
    # tags:
    # - 'v*'
    branches: 
      - master
  # schedule:
  #   - cron: "12 */3 * * *"
  watch:
    types: [started]

jobs:
  build:
    services:
      selenium:
        image: selenium/standalone-chrome
        # Need to change the shm size to avoid the browser crashing inside a docker container, See:
        # https://bugs.chromium.org/p/chromium/issues/detail?id=519952
        # https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot/53970825
        options: --shm-size 2g
        # Health check can make sure the container is healthy, but will slow down the process. Add this back when deployed
        # options: --shm-size 2g --health-cmd '/opt/bin/check-grid.sh'
        ports:
          - 4444:4444
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      # with:
      #   ref: 'init_test'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Requirements
      run: |
        pip install -r requirements.txt
    - name: Selenium Test
      run: |
        python catalogue_downloader.py
    - name: Commit
      run: |
        git config --global user.email update_bot@email.com
        git config --global user.name AutoUpdater
        git add lists
        git diff-index --quiet HEAD || git commit -m "selenium test" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          files/
          logs/
          lists/
